// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: centerms.proto

package cproto

import github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *EventStore) Validate() error {
	return nil
}
func (this *DevMeta) Validate() error {
	return nil
}
func (this *SetDevInitCfgRequest) Validate() error {
	if this.Meta != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Meta); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Meta", err)
		}
	}
	return nil
}
func (this *SetDevInitCfgResponse) Validate() error {
	return nil
}
func (this *SaveDevDataRequest) Validate() error {
	if this.Meta != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Meta); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Meta", err)
		}
	}
	return nil
}
func (this *SaveDevDataResponse) Validate() error {
	return nil
}
