// Code generated by protoc-gen-go. DO NOT EDIT.
// source: centerms.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	centerms.proto

It has these top-level messages:
	DevConfigRequest
	DevMetaRequest
	DevDataRequest
	DevConfigResponse
	DevMetaResponse
	DevDataResponse
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DevConfigRequest struct {
}

func (m *DevConfigRequest) Reset()                    { *m = DevConfigRequest{} }
func (m *DevConfigRequest) String() string            { return proto.CompactTextString(m) }
func (*DevConfigRequest) ProtoMessage()               {}
func (*DevConfigRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type DevMetaRequest struct {
}

func (m *DevMetaRequest) Reset()                    { *m = DevMetaRequest{} }
func (m *DevMetaRequest) String() string            { return proto.CompactTextString(m) }
func (*DevMetaRequest) ProtoMessage()               {}
func (*DevMetaRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type DevDataRequest struct {
}

func (m *DevDataRequest) Reset()                    { *m = DevDataRequest{} }
func (m *DevDataRequest) String() string            { return proto.CompactTextString(m) }
func (*DevDataRequest) ProtoMessage()               {}
func (*DevDataRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type DevConfigResponse struct {
	Mac  string   `protobuf:"bytes,1,opt,name=mac" json:"mac,omitempty"`
	Data [][]byte `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
}

func (m *DevConfigResponse) Reset()                    { *m = DevConfigResponse{} }
func (m *DevConfigResponse) String() string            { return proto.CompactTextString(m) }
func (*DevConfigResponse) ProtoMessage()               {}
func (*DevConfigResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *DevConfigResponse) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

func (m *DevConfigResponse) GetData() [][]byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type DevMetaResponse struct {
	Type string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Mac  string `protobuf:"bytes,3,opt,name=mac" json:"mac,omitempty"`
}

func (m *DevMetaResponse) Reset()                    { *m = DevMetaResponse{} }
func (m *DevMetaResponse) String() string            { return proto.CompactTextString(m) }
func (*DevMetaResponse) ProtoMessage()               {}
func (*DevMetaResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *DevMetaResponse) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *DevMetaResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DevMetaResponse) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

type DevDataResponse struct {
	Site string            `protobuf:"bytes,1,opt,name=site" json:"site,omitempty"`
	Meta *DevMetaResponse  `protobuf:"bytes,2,opt,name=meta" json:"meta,omitempty"`
	Data map[string]string `protobuf:"bytes,3,rep,name=data" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *DevDataResponse) Reset()                    { *m = DevDataResponse{} }
func (m *DevDataResponse) String() string            { return proto.CompactTextString(m) }
func (*DevDataResponse) ProtoMessage()               {}
func (*DevDataResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *DevDataResponse) GetSite() string {
	if m != nil {
		return m.Site
	}
	return ""
}

func (m *DevDataResponse) GetMeta() *DevMetaResponse {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *DevDataResponse) GetData() map[string]string {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*DevConfigRequest)(nil), "pb.DevConfigRequest")
	proto.RegisterType((*DevMetaRequest)(nil), "pb.DevMetaRequest")
	proto.RegisterType((*DevDataRequest)(nil), "pb.DevDataRequest")
	proto.RegisterType((*DevConfigResponse)(nil), "pb.DevConfigResponse")
	proto.RegisterType((*DevMetaResponse)(nil), "pb.DevMetaResponse")
	proto.RegisterType((*DevDataResponse)(nil), "pb.DevDataResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for DevService service

type DevServiceClient interface {
	GetDevsData(ctx context.Context, in *DevDataRequest, opts ...grpc.CallOption) (*DevDataResponse, error)
}

type devServiceClient struct {
	cc *grpc.ClientConn
}

func NewDevServiceClient(cc *grpc.ClientConn) DevServiceClient {
	return &devServiceClient{cc}
}

func (c *devServiceClient) GetDevsData(ctx context.Context, in *DevDataRequest, opts ...grpc.CallOption) (*DevDataResponse, error) {
	out := new(DevDataResponse)
	err := grpc.Invoke(ctx, "/pb.DevService/GetDevsData", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DevService service

type DevServiceServer interface {
	GetDevsData(context.Context, *DevDataRequest) (*DevDataResponse, error)
}

func RegisterDevServiceServer(s *grpc.Server, srv DevServiceServer) {
	s.RegisterService(&_DevService_serviceDesc, srv)
}

func _DevService_GetDevsData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DevDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevServiceServer).GetDevsData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.DevService/GetDevsData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevServiceServer).GetDevsData(ctx, req.(*DevDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DevService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.DevService",
	HandlerType: (*DevServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDevsData",
			Handler:    _DevService_GetDevsData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "centerms.proto",
}

func init() { proto.RegisterFile("centerms.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 287 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xc9, 0x4a, 0xc4, 0x40,
	0x10, 0x86, 0xc9, 0xa2, 0x30, 0x15, 0x19, 0x63, 0x8d, 0x87, 0x30, 0x20, 0x84, 0x5c, 0xcc, 0x29,
	0x60, 0x04, 0xb7, 0xab, 0x2d, 0x1e, 0xc4, 0x4b, 0x7c, 0x82, 0x4e, 0x2c, 0x25, 0x8c, 0x59, 0x4c,
	0xf7, 0x34, 0xe4, 0xd5, 0x7c, 0x3a, 0xe9, 0xce, 0x32, 0x33, 0xe2, 0xed, 0xef, 0x9f, 0xaa, 0xbf,
	0xbe, 0xaa, 0x86, 0x65, 0x41, 0xb5, 0xa4, 0xae, 0x12, 0x49, 0xdb, 0x35, 0xb2, 0x41, 0xbb, 0xcd,
	0x23, 0x04, 0x9f, 0x91, 0x7a, 0x6c, 0xea, 0x8f, 0xf2, 0x33, 0xa3, 0xef, 0x2d, 0x09, 0x19, 0xf9,
	0xb0, 0x64, 0xa4, 0x5e, 0x49, 0xf2, 0x43, 0x87, 0xf1, 0x9d, 0x73, 0x0f, 0x67, 0x7b, 0x7d, 0xa2,
	0x6d, 0x6a, 0x41, 0xe8, 0x83, 0x53, 0xf1, 0x22, 0xb0, 0x42, 0x2b, 0x5e, 0x64, 0x5a, 0x22, 0x82,
	0xfb, 0xce, 0x25, 0x0f, 0xec, 0xd0, 0x89, 0x4f, 0x32, 0xa3, 0xa3, 0x17, 0x38, 0x9d, 0xe3, 0xc7,
	0x46, 0x04, 0x57, 0xf6, 0x2d, 0x8d, 0x9d, 0x46, 0x6b, 0xaf, 0xe6, 0x15, 0x05, 0xf6, 0xe0, 0x69,
	0x3d, 0x0d, 0x70, 0xe6, 0x01, 0xd1, 0x8f, 0x65, 0xd2, 0x06, 0xb4, 0x5d, 0x9a, 0x28, 0xe5, 0x9c,
	0xa6, 0x35, 0x5e, 0x82, 0x5b, 0x91, 0x01, 0xb1, 0x62, 0x2f, 0x5d, 0x25, 0x6d, 0x9e, 0xfc, 0x81,
	0xc8, 0x4c, 0x01, 0x5e, 0x8d, 0xc4, 0x4e, 0xe8, 0xc4, 0x5e, 0x7a, 0x31, 0x16, 0xee, 0xe7, 0x27,
	0xfa, 0xf1, 0x54, 0xcb, 0xae, 0x1f, 0x16, 0x5a, 0xdf, 0xc2, 0x62, 0xb6, 0x34, 0xe2, 0x86, 0xfa,
	0xe9, 0x06, 0x1b, 0xea, 0xf1, 0x1c, 0x8e, 0x14, 0xff, 0xda, 0x4e, 0x9b, 0x0c, 0x8f, 0x07, 0xfb,
	0xce, 0x4a, 0x19, 0x00, 0x23, 0xf5, 0x46, 0x9d, 0x2a, 0x0b, 0xc2, 0x1b, 0xf0, 0x9e, 0x49, 0x32,
	0x52, 0x42, 0xa7, 0x21, 0x1e, 0x8c, 0x36, 0x57, 0x5f, 0xaf, 0xfe, 0xc1, 0xc9, 0x8f, 0xcd, 0x6f,
	0x5e, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x4f, 0x2c, 0x00, 0x38, 0xdf, 0x01, 0x00, 0x00,
}
